// packages/choom-vue/src/components/select/SelectOption.vue
<script>
export default {
  name: "SelectOption",
  render() {
    const p = this.$props;
    const { value, disabled } = p;

    return (
      <option value={value} disabled={disabled}>
        {this.$slots.default()}
      </option>
    );
  },
  props: {
    value: {
      type: String,
      required: true,
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

// packages/choom-svelte/src/components/select/SelectOption.svelte
<script>
  import { Validator } from "../../utils/validator";

  const { required } = new Validator("SelectOption");

  /** @props {string} value */
  export let value;
  required("value", value);

  /** @props {boolean} disabled */
  export let disabled = false;
</script>

<option {value} {disabled}>
  <slot />
</option>
