// packages/choom-react/src/components/flex/FlexUnit.js
import React from "react";
import PropTypes from "prop-types";

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, ClassNames } from "@emotion/react";

import {
  FLEX_ALIGNSELF_TYPES,
  FLEX_JUSTIFY_TYPES,
  FLEX_SIZE_TYPES,
  MAP_SPACE,
  SPACE_TYPES,
} from "choom-theme";

const FlexUnit = ({
  className,
  children,
  as = "div",
  fluid = false,
  stretch = false,
  align = "center",
  justify = "center",
  grow = 1,
  shrink = 1,
  basis = "auto",
  mt = "0",
  mb = "0",
  ml = "0",
  mr = "0",
}) => {
  const spaceT = MAP_SPACE[String(mt)];
  const spaceB = MAP_SPACE[String(mb)];
  const spaceL = MAP_SPACE[String(ml)];
  const spaceR = MAP_SPACE[String(mr)];

  return (
    <ClassNames>
      {({ css, cx }) => {
        return React.createElement(
          as,
          {
            className: cx(
              className,
              css`
                box-sizing: border-box;
                align-self: ${align};
                justify-self: ${justify};
                flex-grow: ${grow};
                flex-shrink: ${shrink};
                flex-basis: ${basis};
                width: ${fluid ? '100%' : 'auto'};
                height: ${stretch ? '100%' : 'auto'};
                margin-top: ${spaceT};
                margin-bottom: ${spaceB};
                margin-left: ${spaceL};
                margin-right: ${spaceR};
              `
            ),
          },
          children
        );
      }}
    </ClassNames>
  );
};

FlexUnit.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node,
  as: PropTypes.string,
  fluid: PropTypes.bool,
  stretch: PropTypes.bool,
  align: PropTypes.oneOf(FLEX_ALIGNSELF_TYPES),
  justify: PropTypes.oneOf(FLEX_JUSTIFY_TYPES),
  grow: PropTypes.oneOf(FLEX_SIZE_TYPES),
  shrink: PropTypes.oneOf(FLEX_SIZE_TYPES),
  basis: PropTypes.string,
  mt: PropTypes.oneOf(SPACE_TYPES),
  mb: PropTypes.oneOf(SPACE_TYPES),
  ml: PropTypes.oneOf(SPACE_TYPES),
  mr: PropTypes.oneOf(SPACE_TYPES),
};

export default FlexUnit;

// packages/choom-vue/src/components/flex/FlexUnit.vue
<script>
import { h, useCssModule } from "vue";
import clsx from "clsx";

import {
  FLEX_ALIGNSELF_TYPES,
  FLEX_JUSTIFY_TYPES,
  FLEX_SIZE_TYPES,
  MAP_SPACE,
  SPACE_TYPES,
} from "choom-theme";

export default {
  name: "FlexUnit",
  setup(p) {
    return {
      cssAlign: p.align,
      cssJustify: p.justify,
      cssGrow: p.grow,
      cssShrink: p.shrink,
      cssBasis: p.basis,
      cssMarginT: MAP_SPACE[String(p.mt)],
      cssMarginB: MAP_SPACE[String(p.mb)],
      cssMarginL: MAP_SPACE[String(p.ml)],
      cssMarginR: MAP_SPACE[String(p.mr)],
    };
  },
  render() {
    const p = this.$props;
    const styles = useCssModule();

    const { as, className, fluid, stretch } = p;

    return h(
      as,
      {
        class: clsx(styles.root, className, {
          [styles.fluid]: fluid,
          [styles.stretch]: stretch,
        }),
      },
      this.$slots.default && this.$slots.default()
    );
  },
  props: {
    className: {
      type: String,
    },
    as: {
      type: String,
      default: "div",
    },
    fluid: {
      type: Boolean,
      default: false,
    },
    stretch: {
      type: Boolean,
      default: false,
    },
    align: {
      validator(value) {
        return [...FLEX_ALIGNSELF_TYPES, "initial"].includes(value);
      },
      default: "center",
    },
    justify: {
      validator(value) {
        return FLEX_JUSTIFY_TYPES.includes(value);
      },
      default: "center",
    },
    grow: {
      validator(value) {
        return FLEX_SIZE_TYPES.includes(value);
      },
      default: 1,
    },
    shrink: {
      validator(value) {
        return FLEX_SIZE_TYPES.includes(value);
      },
      default: 1,
    },
    basis: {
      type: String,
      default: "auto",
    },
    mt: {
      validator(value) {
        return SPACE_TYPES.includes(value);
      },
      default: "0",
    },
    mb: {
      validator(value) {
        return SPACE_TYPES.includes(value);
      },
      default: "0",
    },
    ml: {
      validator(value) {
        return SPACE_TYPES.includes(value);
      },
      default: "0",
    },
    mr: {
      validator(value) {
        return SPACE_TYPES.includes(value);
      },
      default: "0",
    },
  },
};
</script>

<style module lang="scss">
.root {
  box-sizing: border-box;
  align-self: v-bind(cssAlign);
  justify-self: v-bind(cssJustify);
  flex-grow: v-bind(cssGrow);
  flex-shrink: v-bind(cssShrink);
  flex-basis: v-bind(cssBasis);

  width: auto;
  height: auto;

  margin-top: v-bind(cssMarginT);
  margin-bottom: v-bind(cssMarginB);
  margin-left: v-bind(cssMarginL);
  margin-right: v-bind(cssMarginR);
}

.fluid {
  width: 100%;
}

.stretch {
  height: 100%;
}
</style>
