// packages/choom-svelte/src/components/select/SelectOption.svelte
<script>
  import { Validator } from "../../utils/validator";

  const { required } = new Validator("SelectOption");

  /** @props {string} value */
  export let value;
  required("value", value);

  /** @props {boolean} disabled */
  export let disabled = false;
</script>

<option {value} {disabled}>
  <slot />
</option>

// packages/choom-react/src/components/select/SelectOption.js
import React from 'react';

import PropTypes from "prop-types";

const SelectOption = ({ children, value, disabled }) => {
  return (
    <option value={value} disabled={disabled}>
      {children}
    </option>
  );
};

SelectOption.propTypes = {
  children: PropTypes.string.isRequired,
  value: PropTypes.string,
  disabled: PropTypes.bool,
};

export default SelectOption;
