// packages/choom-vue/src/components/media/Media.vue
<script>
import { h, useCssModule } from "vue";

import Flow from "../flow/Flow.vue";
import FlexUnit from "../flex/FlexUnit.vue";

import { FLEX_ALIGN_TYPES, SPACE_TYPES } from "choom-theme";

export default {
  name: "Media",
  components: {
    Flow,
    FlexUnit,
  },
  render() {
    const p = this.$props;
    const styles = useCssModule();

    const { as, asUnit, className, alignContent, alignItems, space } = p;

    return h(
      Flow,
      {
        as,
        class: className,
        alignContent,
        alignItems,
        justifyContent: "start",
        space,
        wrap: false,
      },
      () => [
        this.$slots.start && (
          <FlexUnit
            as={asUnit}
            grow="0"
            shrink="1"
            align="initial"
            className={styles.start}
          >
            {this.$slots.start()}
          </FlexUnit>
        ),
        this.$slots.default && (
          <FlexUnit
            as={asUnit}
            grow="1"
            shrink="1"
            align="initial"
            className={styles.main}
          >
            {this.$slots.default()}
          </FlexUnit>
        ),
        this.$slots.end && (
          <FlexUnit
            as={asUnit}
            grow="0"
            shrink="1"
            align="initial"
            className={styles.end}
          >
            {this.$slots.end()}
          </FlexUnit>
        ),
      ]
    );
  },
  props: {
    className: {
      type: String,
    },
    as: {
      type: String,
      default: "div",
    },
    asUnit: {
      type: String,
      default: "div",
    },
    alignContent: {
      validator(value) {
        return [...FLEX_ALIGN_TYPES, "initial"].includes(value);
      },
      default: "center",
    },
    alignItems: {
      validator(value) {
        return [...FLEX_ALIGN_TYPES, "initial"].includes(value);
      },
      default: "center",
    },
    space: {
      validator(value) {
        return SPACE_TYPES.includes(value);
      },
      default: "1",
    },
  },
};
</script>

<style module lang="scss">
.start,
.main,
.end {
  display: inline-flex;
}
</style>

// packages/choom-react/src/components/media/Media.js
import React from "react";
import PropTypes from "prop-types";

import Flow from "../flow/Flow";
import FlexUnit from "../flex/FlexUnit";

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, ClassNames } from "@emotion/react";

import { FLEX_ALIGN_TYPES, SPACE_TYPES } from "choom-theme";

const Media = ({
  className,
  children,
  as = "div",
  asUnit = "div",
  align = "start",
  start = null,
  end = null,
  space = "1",
}) => {
  return (
    <ClassNames>
      {({ css, cx }) => {
        return (
          <Flow
            as={as}
            align={align}
            justify="start"
            wrap={false}
            space={space}
            className={className}
          >
            {start && (
              <FlexUnit
                as={asUnit}
                grow="0"
                shrink="1"
                align={align}
                className={cx(
                  css`
                    display: inline-flex;
                  `
                )}
              >
                {start}
              </FlexUnit>
            )}
            {children && (
              <FlexUnit
                as={asUnit}
                grow="1"
                shrink="1"
                align={align}
                className={cx(
                  css`
                    display: inline-flex;
                  `
                )}
              >
                {children}
              </FlexUnit>
            )}
            {end && (
              <FlexUnit
                as={asUnit}
                grow="0"
                shrink="1"
                align={align}
                className={cx(
                  css`
                    display: inline-flex;
                  `
                )}
              >
                {end}
              </FlexUnit>
            )}
          </Flow>
        );
      }}
    </ClassNames>
  );
};

Media.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
  start: PropTypes.node,
  end: PropTypes.node,
  as: PropTypes.string,
  asUnit: PropTypes.string,
  align: PropTypes.oneOf(FLEX_ALIGN_TYPES),
  space: PropTypes.oneOf(SPACE_TYPES),
};

export default Media;
