// packages/choom-svelte/src/components/contain/Contain.svelte
<script>
  import clsx from "clsx";

  import {
    DIRECTION_TYPES,
    MAP_SPACE,
    SPACE_TYPES,
  } from "choom-theme";

  import { propsToVars } from "../../utils/propsToVars";
  import { Validator } from "../../utils/validator";

  const { validate } = new Validator("Contain");

  /** @props {string} className */
  export let className = "";

  /** @props {string} as */
  export let as = "div";

  /** @props {string} dir */
  export let dir = "xy";
  validate("dir", dir, DIRECTION_TYPES);

  /** @props {string} padding */
  export let space = "1";
  validate("space", space, SPACE_TYPES);

  const spaceValue = MAP_SPACE[String(space)];

  let padT = 0;
  let padB = 0;
  let padL = 0;
  let padR = 0;

  switch (dir) {
    case "xy":
      padT = padB = padL = padR = spaceValue;
      break;

    case "x":
      padL = padR = spaceValue;
      break;

    case "y":
      padT = padB = spaceValue;
      break;

    case "top":
      padT = spaceValue;
      break;

    case "bottom":
      padB = spaceValue;
      break;

    case "left":
      padL = spaceValue;
      break;

    case "right":
      padR = spaceValue;
      break;
  }

  export let css = {};

  if (padT !== 0) {
    css.Contain_PaddingT = padT;
  }

  if (padB !== 0) {
    css.Contain_PaddingB = padB;
  }

  if (padL !== 0) {
    css.Contain_PaddingL = padL;
  }

  if (padR !== 0) {
    css.Contain_PaddingR = padR;
  }

  export const p = {
    class: clsx("root", className),
    style: propsToVars(css),
  };
</script>

{#if as === "section"}
  <section {...p}><slot /></section>
{:else if as === "article"}
  <article {...p}><slot /></article>
{:else if as === "aside"}
  <aside {...p}><slot /></aside>
{:else}
  <div {...p}><slot /></div>
{/if}

<style lang="scss">
  .root {
    box-sizing: border-box;
    width: 100%;
    padding-top: var(--Contain_PaddingT, 0);
    padding-bottom: var(--Contain_PaddingB, 0);
    padding-left: var(--Contain_PaddingL, 0);
    padding-right: var(--Contain_PaddingR, 0);
  }
</style>

// packages/choom-react/src/components/contain/Contain.js
import React from "react";
import PropTypes from "prop-types";

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, css, ClassNames } from "@emotion/react";

import { MAP_SPACE, SPACE_TYPES, DIRECTION_TYPES } from "choom-theme";

const Contain = ({
  className,
  children,
  as = "div",
  dir = "xy",
  space = "1",
}) => {
  const spaceValue = MAP_SPACE[String(space)];

  let padT = 0;
  let padB = 0;
  let padL = 0;
  let padR = 0;

  switch (dir) {
    case "xy":
      padT = padB = padL = padR = spaceValue;
      break;

    case "x":
      padL = padR = spaceValue;
      break;

    case "y":
      padT = padB = spaceValue;
      break;

    case "top":
      padT = spaceValue;
      break;

    case "bottom":
      padB = spaceValue;
      break;

    case "left":
      padL = spaceValue;
      break;

    case "right":
      padR = spaceValue;
      break;
  }

  return (
    <ClassNames>
      {({ css, cx }) => {
        return React.createElement(
          as,
          {
            className: cx(
              className,
              css`
                box-sizing: border-box;
                width: 100%;
                padding-top: ${padT};
                padding-bottom: ${padB};
                padding-left: ${padL};
                padding-right: ${padR};
              `
            ),
          },
          children
        );
      }}
    </ClassNames>
  );
};

Contain.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
  as: PropTypes.string,
  dir: PropTypes.oneOf(DIRECTION_TYPES),
  space: PropTypes.oneOf(SPACE_TYPES),
};

export default Contain;
