// packages/choom-react/src/components/switch/Switch.js
import PropTypes from "prop-types";

import { useState, useRef } from "react";

/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from "@emotion/react";
import { nanoid } from "nanoid";

import theme from "../../theme/theme";

const Switch = ({
  className,
  name,
  disabled = false,
  checked = false,
  onChange = () => null,
}) => {
  const _id = useRef(nanoid());

  const [isChecked, setIsChecked] = useState(checked);

  const handleChange = () => {
    if (disabled) return;

    const _checked = !isChecked;

    setIsChecked(_checked);
    onChange(_checked);
  };

  return (
    <label
      css={css`
        box-sizing: content-box;
        display: inline-flex;
        vertical-align: middle;

        position: relative;
        height: ${theme.spaceOneAndHalf};
        width: ${theme.spaceFour};

        border: ${theme.borderSizeRegular} solid ${theme.colorDarkTemp};
        border-radius: ${theme.spaceOne};

        background: ${isChecked ? theme.colorThemeTemp : theme.colorLightTemp};
        color: ${theme.colorDarkTemp};

        cursor: pointer;
        transition: all 0.15s;

        ${
          !disabled &&
          `
          @media (hover: hover) {
            &:hover {
              filter: brightness(1.2);
            }
          }

          &:active:not([disabled]) {
            transform: scale(0.925);
          }
          `
        }

        ${
          disabled &&
          `
          cursor: default;
          opacity: 0.5;
          `
        }
          
        }
      `}
      htmlFor={_id.current}
    >
      <input
        id={_id.current}
        className={className}
        name={name}
        css={css`
          width: 0;
          height: 0;
          opacity: 0;
          position: absolute;
          pointer-events: none;
        `}
        onChange={handleChange}
        checked={isChecked}
        disabled={disabled}
        type="checkbox"
      />
      <span
        css={css`
          box-sizing: content-box;
          position: absolute;
          top: calc(
            -1 * ${theme.borderSizeRegular} - 1 * ${theme.spaceQuarter}
          );
          left: calc(-1 * ${theme.borderSizeRegular});

          width: ${theme.spaceTwo};
          height: ${theme.spaceTwo};

          border: ${theme.borderSizeRegular} solid ${theme.colorDarkTemp};
          border-radius: ${theme.spaceOne};

          background: ${theme.colorLightTemp};

          transform: ${isChecked
            ? "translateX(calc(100% - " + theme.borderSizeRegular + " * 2))"
            : "translateX(0)"};
          transition: transform 0.15s;
        `}
      />
    </label>
  );
};

Switch.propTypes = {
  className: PropTypes.string,
  name: PropTypes.string,
  disabled: PropTypes.bool,
  checked: PropTypes.bool,
  onChange: PropTypes.func,
};

export default Switch;

// packages/choom-svelte/src/components/switch/Switch.svelte
<script>
  import { nanoid } from 'nanoid/non-secure';

  /** @props {string} className */
  export let className = '';

  /** @props {boolean} disabled */
  export let disabled = false;

  /** @props {boolean} checked */
  export let checked = false;

  /** @props {string} name */
  export let name = undefined;

  /** @props {function} onChange */
  export let onChange = () => null;

  export const id = nanoid();

  function handleChange(e) {
    onChange(checked, e.target);
  }
</script>

<label
  class={className}
  class:isDisabled={disabled}
  class:isEnabled={!disabled}
  class:isChecked={checked}
  for={id}
>
  <input
    type="checkbox"
    readonly
    {id}
    {name}
    {disabled}
    bind:checked
    on:change={handleChange}
  />
  <span class="toggle" />
</label>

<style lang="scss">
  label {
    box-sizing: content-box;
    display: inline-flex;
    vertical-align: middle;

    position: relative;
    height: var(--space-one-and-half);
    width: var(--space-four);

    border: var(--border-size-regular) solid var(--color-dark-temp);
    border-radius: var(--space-one);

    background: var(--color-light-temp);
    color: var(--color-dark-temp);

    cursor: pointer;
    transition: all 0.15s;
  }

  .isChecked {
    background: var(--color-theme-temp);
  }

  .isDisabled {
    cursor: default;
    opacity: 0.5;
  }

  .isEnabled {
    @media (hover: hover) {
      &:hover {
        filter: brightness(1.2);
      }
    }

    &:active:not([disabled]) {
      transform: scale(0.925);
    }
  }

  input {
    width: 0;
    height: 0;

    opacity: 0;
    position: absolute;
    pointer-events: none;
  }

  input + span {
    box-sizing: content-box;
    position: absolute;
    top: calc(-1 * var(--border-size-regular) - 1 * var(--space-quarter));
    left: calc(-1 * var(--border-size-regular));

    width: var(--space-two);
    height: var(--space-two);

    border: var(--border-size-regular) solid var(--color-dark-temp);
    border-radius: var(--space-one);

    background: var(--color-light-temp);

    transform: translateX(0);
    transition: transform 0.15s;

    .isChecked & {
      transform: translateX(calc(100% - var(--border-size-regular) * 2));
    }
  }
</style>
