// packages/choom-svelte/src/components/stack/Stack.svelte
<script>
  import clsx from "clsx";

  import {
    DIRECTION_XY_TYPES,
    MAP_SPACE,
    SPACE_TYPES,
  } from "choom-theme";

  import { propsToVars } from "../../utils/propsToVars";
  import { Validator } from "../../utils/validator";

  const { validate } = new Validator("Stack");

  /** @props {string} className */
  export let className = "";

  /** @props {string} as */
  export let as = "div";

  /** @props {string} dir */
  export let dir = "y";
  validate("dir", dir, DIRECTION_XY_TYPES);

  /** @props {string} padding */
  export let space = "1";
  validate("space", space, SPACE_TYPES);

  const spaceValue = MAP_SPACE[String(space)];

  let marginL = spaceValue;
  let marginT = spaceValue;

  export let css = {};

  if (dir === "y") {
    css.Stack_MarginT = marginT;
  }

  if (dir === "x") {
    css.Stack_MarginL = marginL;
  }

  export const p = {
    class: clsx("root", className),
    style: propsToVars(css),
  };
</script>

{#if as === "section"}
  <section {...p}><slot /></section>
{:else if as === "article"}
  <article {...p}><slot /></article>
{:else if as === "aside"}
  <aside {...p}><slot /></aside>
{:else}
  <div {...p}><slot /></div>
{/if}

<style lang="scss">
  .root {
    box-sizing: border-box;
    width: 100%;

    & > :global(*:not(:first-child)) {
      margin-top: var(--Stack_MarginT);
      margin-left: var(--Stack_MarginL);
    }
  }
</style>

// packages/choom-react/src/components/stack/Stack.js
import React from "react";
import PropTypes from "prop-types";

/** @jsxRuntime classic */
/** @jsx jsx */
import { jsx, css, ClassNames } from "@emotion/react";

import {
  DIRECTION_XY_TYPES,
  MAP_SPACE,
  SPACE_TYPES,
} from "choom-theme";

const Stack = ({ className, children, as = "div", dir = "y", space = "1" }) => {
  const spaceValue = MAP_SPACE[String(space)];

  let marginL = spaceValue;
  let marginT = spaceValue;

  if (dir === 'y') {
    marginL = 0;
  }

  if (dir === 'x') {
    marginT = 0;
  }

  return (
    <ClassNames>
      {({ css, cx }) => {
        return React.createElement(
          as,
          {
            className: cx(
              className,
              css`
                box-sizing: border-box;
                width: 100%;
                overflow: hidden;
              `
            ),
          },
          <div css={css`
            ${
              marginT !== 0 && 
              `margin-top: calc(-1 * ${marginT});`
            }
            ${
              marginL !== 0 &&
              `margin-left: calc(-1 * ${marginL});`
            }

            /* extra specificity over descendants */
            && > * {
              margin-top: ${marginT};
              margin-left: ${marginL};
            }
          `}>{children}</div>
        );
      }}
    </ClassNames>
  );
};

Stack.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
  as: PropTypes.string,
  dir: PropTypes.oneOf(DIRECTION_XY_TYPES),
  space: PropTypes.oneOf(SPACE_TYPES),
};

export default Stack;
