// packages/choom-react/src/components/picture/Picture.js
import PropTypes from "prop-types";

/** @jsxRuntime classic */
/** @jsx jsx */
import { css, jsx } from "@emotion/react";
import { Image } from "react-feather";

import theme, { ASPECT_RATIO_TYPES, IMG_FIT_TYPES } from "choom-theme";

import Hold from '../hold/Hold';
import Icon from '../icon/Icon';

const getUnit = (strValue) => strValue.match(/[a-z, %]+$/)[0] || "";
const parseAspectRatio = (strValue) => {
  const [wx, hx] = strValue.split(":");

  return [Number(wx), Number(hx)];
};

const Picture = ({
  className,
  alt = "",
  src,
  width = "auto",
  height = "auto",
  aspectRatio = "",
  fill = "cover",
}) => {
  let widthValue = "";
  let heightValue = "";

  if (width !== undefined) widthValue = width;
  if (height !== undefined) heightValue = height;

  if (aspectRatio) {
    const [wx, hx] = parseAspectRatio(aspectRatio);

    if (widthValue && heightValue === "auto") {
      let unit = getUnit(widthValue);

      heightValue = (parseInt(widthValue, 10) / wx) * hx;
      heightValue = `${Math.round(heightValue)}${unit}`;
    } else if (heightValue && widthValue === "auto") {
      let unit = getUnit(heightValue);

      widthValue = (parseInt(heightValue, 10) / hx) * wx;
      widthValue = `${Math.round(widthValue)}${unit}`;
    }
  }

  return (
    <figure
      className={className}
      css={css`
        display: inline-flex;
        box-sizing: border-box;
        margin: 0;

        border: ${theme.borderSizeRegular} solid ${theme.colorLightTemp};
        border-radius: ${theme.radiusRegular};
        overflow: hidden;
        width: ${widthValue};
        height: ${heightValue};

        background: ${theme.colorLightTemp};

        line-height: 0;
        font-size: 0;

        cursor: default;
        user-select: none;
      `}
    >
      {!!src ? (
        <img
          alt={alt}
          css={css`
            object-fit: ${fill};
            width: 100%;
            height: 100%;
          `}
          src={src}
        />
      ) : (
        <Hold>
          <span
            css={css`
            opacity: 0.25;
            color: ${theme.colorDarkTemp};
          `}
          >
            <Icon>
              <Image />
            </Icon>
          </span>
        </Hold>
      )}
    </figure>
  );
};

Picture.propTypes = {
  className: PropTypes.string,
  alt: PropTypes.string,
  src: PropTypes.string.isRequired,
  width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  aspectRatio: PropTypes.oneOf(ASPECT_RATIO_TYPES),
  fill: PropTypes.oneOf(IMG_FIT_TYPES),
};

export default Picture;

// packages/choom-vue/src/components/picture/Picture.vue
<script>
import { h, readonly, useCssModule } from "vue";
import clsx from "clsx";

import Icon from "../icon/Icon.vue";

import { PhotoIcon } from "vue-tabler-icons";

import { ASPECT_RATIO_TYPES, IMG_FIT_TYPES } from "choom-theme";

const getUnit = (strValue) => strValue.match(/[a-z, %]+$/)[0] || "";
const parseAspectRatio = (strValue) => {
  const [wx, hx] = strValue.split(":");

  return [Number(wx), Number(hx)];
};

export default {
  name: "Picture",
  components: {
    Icon,
    PhotoIcon,
  },
  setup(p) {
    let widthValue = "";
    let heightValue = "";

    const state = readonly({
      width: p.width,
      height: p.height
    });

    if (p.width !== undefined) widthValue = state.width;
    if (p.height !== undefined) heightValue = state.height;

    if (p.aspectRatio) {
      const [wx, hx] = parseAspectRatio(p.aspectRatio);

      if (widthValue && heightValue === "auto") {
        let unit = getUnit(widthValue);

        heightValue = (parseInt(widthValue, 10) / wx) * hx;
        heightValue = `${Math.round(heightValue)}${unit}`;
      } else if (heightValue && widthValue === "auto") {
        let unit = getUnit(heightValue);

        widthValue = (parseInt(heightValue, 10) / hx) * wx;
        widthValue = `${Math.round(widthValue)}${unit}`;
      }
    }

    return {
      cssWidth: widthValue,
      cssHeight: heightValue,
      cssFill: p.fill,
    };
  },
  render() {
    const p = this.$props;
    const styles = useCssModule();

    const { className, src, alt } = p;

    const img = h("img", {
      class: styles.img,
      alt,
      src,
    });

    const ph = h(
      "span",
      {
        class: styles.ph,
      },
      <Icon>
        <PhotoIcon />
      </Icon>
    );

    return h(
      "figure",
      {
        class: clsx(styles.root, className),
      },
      src ? img : ph
    );
  },
  props: {
    className: {
      type: String,
    },
    alt: {
      type: String,
      default: "",
    },
    src: {
      type: String,
      required: true,
    },
    width: {
      type: [String, Number],
      default: "auto",
    },
    height: {
      type: [String, Number],
      default: "auto",
    },
    aspectRatio: {
      validator(value) {
        return ASPECT_RATIO_TYPES.includes(value);
      },
      default: "",
    },
    fill: {
      validator(value) {
        return IMG_FIT_TYPES.includes(value);
      },
      default: "cover",
    },
  },
};
</script>

<style module lang="scss">
.root {
  display: inline-flex;
  box-sizing: border-box;

  width: v-bind("cssWidth || auto");
  height: v-bind("cssHeight || auto");
  margin: 0;

  border: var(--border-size-regular) solid var(--color-light-temp);
  border-radius: var(--radius-regular);
  overflow: hidden;

  background: var(--color-light-temp);

  line-height: 0;
  font-size: 0;

  cursor: default;
  user-select: none;
}

.img {
  object-fit: v-bind(cssFill);
  width: 100%;
  height: 100%;
}

.ph {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  opacity: 0.25;
  color: var(--color-dark-temp);
}
</style>
